name: Android Auto Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 'adopt@1.20'  # 指定 Java 20 版本

    - name: Build with Gradle
      run: ./gradlew build

    - name: Package APK
      run: ./gradlew bundleRelease
